version: "2"
networks:
    compose_fab-net:
        driver: bridge
        ipam:
            config:
                - subnet: "${DOCKER_SUBNET}"
services:
    kafka:
        image: "${KAFKA_IMAGE}"
        # volumes:
        #     - /home/k2view/VOLUMES-DONT-DELETE/kafka:/home/kafka/data
        networks:
            compose_fab-net:
                ipv4_address: "${KAFKA_IP}"
        user: kafka
        container_name: kafka
        ports:
            - "9093:9093"
            - "2181:2181"
            - "3888:3888"
        environment:
            K2_HOME: "${KAFKA_HOME}"
            KAFKA_ZK: "${KAFKA_IP}"
            KAFKA_IP: "${KAFKA_IP_WITH_PORT}"
            KAFKA_HOSTLIST: "${KAFKA_HOSTLIST}"
            KAFKA_ZK_CON: "${KAFKA_ZK_CON}"
        entrypoint:
            - bash
            - -l
            - -c
            - "(/opt/apps/kafka/init.sh &) && sleep INFINITY"
   
    cassandra:
        image: "${CASSANDRA_IMAGE}"
        # volumes:
        #     - /home/k2view/VOLUMES-DONT-DELETE/cassandra1:/home/cassandra/storage
        networks:
            compose_fab-net:
                ipv4_address: "${CASSANDRA_IP}"
        privileged: true
        container_name: cassandra
        ports:
            - "7000:7000"
            - "7001:7001"
            - "7199:7199"
            - "9042:9042"
            - "9160:9160"
        environment:
            # Declare here the dc you working with
            DC_NAME: "DC1"
            CASSANDRA_IP: "${CASSANDRA_IP}"
            INSLATT_DIR : "${CASSANDRA_HOME}"
            FIRST_CASSANDRA_IP: "${FIRST_CASSANDRA_IP}"
        entrypoint:
            - bash
            - -l
            - -c
            - '(/opt/apps/cassandra/init.sh &) && sleep INFINITY'
   
    fabric:
        image: "${FABRIC_IMAGE}"
        # volumes:
        #     - /home/k2view/VOLUMES-DONT-DELETE/fabric:/usr/local/k2view/storage
        user: "${CONTAIENR_USER}"
        networks:
            compose_fab-net:
                ipv4_address: "${FABRIC_IP}"
        privileged: true
        container_name: fabric
        ports:
            - "3213:3213"
            - "5124:5124"
            - "4001:4001"
            - "3000:3000"
            - "6379:6379"
        depends_on:
            - "cassandra"
            - "kafka"
        environment:
            COMPOSE_HTTP_TIMEOUT: 200
            K2_HOME_DOCKER: "${K2_HOME_DOCKER}"
            SEED_IP: "${SEED_IP}"
            FABRIC_IP: "${FABRIC_IP}"
            KAFKA_IP: "${KAFKA_IP}"
            # Set your cluster name
            CLUSTER_NAME: fabric_cluster
            AUTH_REPLICATION_FACTOR: "${AUTH_REPLICATION_FACTOR}"
            NUM_OF_NODES: "${NUM_OF_NODES}"
            # Declare here the dc you working with
            DC_NAME: DC1
            RACK: "${RACK}"
            MAX_HEAP_SIZE: "${MAX_HEAP_SIZE}"
            HEAP_NEWSIZE: "${HEAP_NEWSIZE}"
            PG_HOST: "${PG_IP}"
            PG_PORT: "${PG_PORT}"
            PG_USER: "${PG_USER}"
            DB: "${DB}"
            PGPASSWORD: "${PGPASSWORD}"
            LDAP_PUBLIC_IP: "${LDAP_PUBLIC_IP}"
            TDM_PUBLIC_IP: "${TDM_Public_IP}"
            liveliness: "${liveliness}"
            liveliness_interval: "${liveliness_interval}"
        entrypoint:
            - bash
            - -l
            - -c
            - '(cp -r /usr/local/k2view/fabric/config.template /usr/local/k2view/config) && (sed -i s/"#HOSTS=.*"/"HOSTS=$${SEED_IP}"/g /usr/local/k2view/config/config.ini) && (sed -i "s@#USER=.*@USER=cassandra@" /usr/local/k2view/config/config.ini) && (sed -i "s@#PASSWORD=.*@PASSWORD=cassandra@" /usr/local/k2view/config/config.ini) && (sed -i "s@#MESSAGES_BROKER_TYPE=.*@MESSAGES_BROKER_TYPE=KAFKA@" /usr/local/k2view/config/config.ini) && (sed -i "s@#BOOTSTRAP_SERVERS=.*@BOOTSTRAP_SERVERS=$${KAFKA_IP}:9093@" /usr/local/k2view/config/config.ini) && (sleep 40) && (k2fabric start) && (sleep INFINITY)'
   